id: ICA793FC9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:58:04+00:00'
last_modified: '2022-06-09T04:49:02.292062+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23629
  title: གསུང་འབུམ། གཞོན་ནུ་བློ་གྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    68D4:
      image_group_id: I3503
      title: ''
      total_pages: 560
      order: 1
      base_file: 68D4.txt
    3A00:
      image_group_id: I3504
      title: ''
      total_pages: 478
      order: 2
      base_file: 3A00.txt
    976F:
      image_group_id: I1KG12209
      title: ''
      total_pages: 836
      order: 3
      base_file: 976F.txt
    '4552':
      image_group_id: I1KG12210
      title: ''
      total_pages: 394
      order: 4
      base_file: 4552.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
