id: P008145
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:25.761398
source_metadata:
  id: bdr:W23629
  title: གསུང་འབུམ། གཞོན་ནུ་བློ་གྲོས།
  author: ''
  volumes:
    97de965051ff4e248f4457c7d003752e:
      image_group_id: I1KG12209
      title: ''
      volume_number: 3
      total_pages: 836
    b67ea788522a469cbf0bec0654e3c526:
      image_group_id: I1KG12210
      title: ''
      volume_number: 4
      total_pages: 394
    f94e6e863c66465caebcfb826bf92817:
      image_group_id: I3503
      title: ''
      volume_number: 1
      total_pages: 560
      base_file: v003.txt
    8f146b0eb04d4c908d12e03f68a4ada9:
      image_group_id: I3504
      title: ''
      volume_number: 2
      total_pages: 478
      base_file: v004.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
